# Generated by Django 6.0.3 on 2026-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型标识')),
                ('title', models.CharField(max_length=200, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('toml', 'TOML')], default='json', max_length=10, verbose_name='格式')),
                ('schema', models.JSONField(default=dict, verbose_name='JSON Schema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config_type',
                'ordering': ['-created_at'],
            },
        ),
    ]
