# Generated by Django 4.2.29 on 2026-03-22 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_permission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='角色描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='权限列表')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户列表')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='SmartPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='权限名称，如：配置实例.新建配置实例', max_length=255, verbose_name='name')),
                ('codename', models.CharField(default='', max_length=100, verbose_name='codename')),
                ('description', models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='权限描述')),
                ('permission_type', models.CharField(choices=[('menu', '菜单权限'), ('button', '按钮权限')], default='button', max_length=20, verbose_name='权限类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(default=smart_permission.models.get_smart_permission_content_type, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'smart_permission',
                'verbose_name_plural': 'smart_permissions',
                'db_table': 'smart_permission',
                'ordering': ['name'],
                'unique_together': {('content_type', 'codename')},
            },
        ),
    ]
