# Generated by Django 4.2.29 on 2026-03-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='菜单标识')),
                ('title', models.CharField(max_length=100, verbose_name='菜单标题')),
                ('path', models.CharField(max_length=200, verbose_name='路由路径')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标名称')),
                ('component', models.CharField(blank=True, default='', help_text='Vue组件名称，如 ConfigTypeList, ConfigInstanceList', max_length=100, verbose_name='组件名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='smart_permission.menu', verbose_name='父菜单')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_permission.smartpermission', verbose_name='关联权限')),
            ],
            options={
                'verbose_name': '菜单配置',
                'verbose_name_plural': '菜单配置',
                'db_table': 'smart_menu',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
