# Generated by Django 6.0.3 on 2026-03-22 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_instance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('format', models.CharField(max_length=10, verbose_name='格式')),
                ('content_text', models.TextField(verbose_name='原始内容')),
                ('parsed_data', models.JSONField(default=dict, verbose_name='解析后数据')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更说明')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config_instance.configinstance')),
            ],
            options={
                'db_table': 'config_version',
                'ordering': ['-version'],
                'unique_together': {('config', 'version')},
            },
        ),
    ]
