# Generated by Django 6.0.3 on 2026-03-22 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('toml', 'TOML')], default='json', max_length=10, verbose_name='格式')),
                ('content_text', models.TextField(verbose_name='原始内容')),
                ('parsed_data', models.JSONField(default=dict, verbose_name='解析后数据')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_type.configtype', verbose_name='配置类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'config_instance',
                'ordering': ['-updated_at'],
                'unique_together': {('config_type', 'name')},
            },
        ),
    ]
