# Generated by Django 6.0.3 on 2026-03-22 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('VIEW', '查看'), ('EXPORT', '导出'), ('IMPORT', '导入')], max_length=20, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=100, verbose_name='资源ID')),
                ('resource_name', models.CharField(max_length=200, verbose_name='资源名称')),
                ('details', models.JSONField(default=dict, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
